spring: 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.101:3306/cfdb?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://localhost:3306/cfdb?autoReconnect=true&useunicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 9090
mybatis: 
  config-location: classpath:mybatis-config.xml